server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 805757125729-sj1antm0mp886k064m8dmv7g51ta4hv8.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://web-study.cdunfdqk1xmg.ap-northeast-2.rds.amazonaws.com:3306/notice?useUnicode=true&characterEncoding=UTF-8"
    username: "admin"
    password: "1q2w3e4r"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
            
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: C:/Users/molla/Desktop/Coding/JAVA/practice/upload/